version: '3.8'

services:
  mariadb_db:
    image: mariadb:latest
    container_name: mariadb_spring_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: jira_ai_integration
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: