# Use uma imagem base da Microsoft que já vem com muitas ferramentas
FROM mcr.microsoft.com/devcontainers/java:17-bullseye

# Instala o Maven (a imagem base já tem JDK e outras ferramentas)
RUN sudo apt-get update && sudo apt-get install -y maven