spring.application.name=jira-ai-integration

# ======== GOOGLE GENERATIVE AI CONFIGURATION ========
spring.ai.google.genai.api-key=AIzaSyC15N8r4hbeckhLNtrkU6YiDUjAB1cb8Ko
spring.ai.google.genai.chat.options.model=gemini-2.0-flash
spring.ai.google.genai.chat.options.temperature=0.5


# ======== JIRA CONFIGURATION ========
jira.url=https://renysoo.atlassian.net
jira.username=rml2@cesar.school
# Cole aqui o token gerado no passo 1
jira.token=ATATT3xFfGF0jPvKOAoIgAm7jdgaoOfk9aK-ZAakt_ZaF18hol8MaGUKl2xEad2ARIZVtlbdLTEE46ZiUBIAjpIa_G9QX85FfDUk3JX0o6_QbEJmqVUGYXU-yAsyEBTAlagogUZxVYq_1ZOdyQvbkvA8OajaAjMwqHPHlU3wQVfw5fRuQgwcxdI=1EF638F1
# Ativa o perfil de desenvolvimento.
spring.profiles.active=dev

# ======== DATA SOURCE CONFIGURATION ========
# ======== H2 DATABASE ===========
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## ========= MARIA DB ===========
#spring.datasource.url=jdbc:mariadb://localhost:3306/jira_ai_integration

#spring.datasource.username=jira_app_user
#spring.datasource.password=EquipeKant
#
## Driver JDBC
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#
#spring.jpa.hibernate.ddl-auto=validate
#
## Opcional: Mostra os comandos SQL no console (bom para debug)
#spring.jpa.show-sql=true
